// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/download": {
            "post": {
                "description": "Avvia un task di download in background e restituisce immediatamente l'ID del task",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Download"
                ],
                "summary": "Avvia download asincrono",
                "parameters": [
                    {
                        "description": "Parametri di download",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.DownloadRequest"
                        }
                    }
                ],
                "responses": {
                    "202": {
                        "description": "Contiene task_id, status e message",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Richiesta malformata",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/download/sync": {
            "post": {
                "description": "Avvia il download e si blocca finché tutti i file non sono stati scaricati e taggati",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Download"
                ],
                "summary": "Avvia download sincrono",
                "parameters": [
                    {
                        "description": "Parametri di download",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.DownloadRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Contiene status e l'elenco dei file",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Richiesta malformata",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Errore durante il download",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/health": {
            "get": {
                "description": "Verifica se il server API è attivo e funzionante",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "System"
                ],
                "summary": "Health Check",
                "responses": {
                    "200": {
                        "description": "status ok",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/status/{id}": {
            "get": {
                "description": "Restituisce lo stato attuale di un download asincrono specificando l'ID del task",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Download"
                ],
                "summary": "Traccia lo stato del task",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID del task",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Task"
                        }
                    },
                    "404": {
                        "description": "Task non trovato",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "models.DownloadRequest": {
            "type": "object",
            "properties": {
                "album_artist": {
                    "type": "string"
                },
                "album_name": {
                    "type": "string"
                },
                "artist_name": {
                    "type": "string"
                },
                "filename_format": {
                    "type": "string"
                },
                "isrc": {
                    "type": "string"
                },
                "output_dir": {
                    "type": "string"
                },
                "quality": {
                    "type": "string"
                },
                "release_date": {
                    "type": "string"
                },
                "service": {
                    "type": "string"
                },
                "spotify_id": {
                    "type": "string"
                },
                "track_name": {
                    "type": "string"
                },
                "url": {
                    "type": "string"
                }
            }
        },
        "models.Task": {
            "type": "object",
            "properties": {
                "completed_tracks": {
                    "type": "integer"
                },
                "created_at": {
                    "type": "string"
                },
                "current_track": {
                    "type": "string"
                },
                "downloaded_files": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "error": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "quality": {
                    "type": "string"
                },
                "service": {
                    "type": "string"
                },
                "spotify_url": {
                    "type": "string"
                },
                "status": {
                    "$ref": "#/definitions/models.TaskStatus"
                },
                "total_tracks": {
                    "type": "integer"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "models.TaskStatus": {
            "type": "string",
            "enum": [
                "pending",
                "resolving",
                "downloading",
                "completed",
                "failed"
            ],
            "x-enum-varnames": [
                "StatusPending",
                "StatusResolving",
                "StatusDownloading",
                "StatusCompleted",
                "StatusFailed"
            ]
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "SpotiFLAC REST API",
	Description:      "A lightweight REST API wrapper for the SpotiFLAC backend.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
