// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/download": {
            "post": {
                "description": "Avvia un task di download in background e restituisce immediatamente l'ID del task",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Download"
                ],
                "summary": "Avvia download asincrono",
                "parameters": [
                    {
                        "description": "Parametri di download",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.DownloadRequest"
                        }
                    }
                ],
                "responses": {
                    "202": {
                        "description": "Contiene task_id, status e message",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Richiesta malformata",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/download/sync": {
            "post": {
                "description": "Avvia il download e si blocca finché tutti i file non sono stati scaricati e taggati",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Download"
                ],
                "summary": "Avvia download sincrono",
                "parameters": [
                    {
                        "description": "Parametri di download",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.DownloadRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Contiene status e l'elenco dei file",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Richiesta malformata",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Errore durante il download",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/health": {
            "get": {
                "description": "Verifica se il server API è attivo e funzionante",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "System"
                ],
                "summary": "Health Check",
                "responses": {
                    "200": {
                        "description": "status ok",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/status/{id}": {
            "get": {
                "description": "Restituisce lo stato attuale di un download asincrono specificando l'ID del task",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Download"
                ],
                "summary": "Traccia lo stato del task",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID del task",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Task"
                        }
                    },
                    "404": {
                        "description": "Task non trovato",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "models.DownloadRequest": {
            "type": "object",
            "properties": {
                "album_artist": {
                    "description": "Artista dell'album. Facoltativo, usato per la scrittura dei tag ID3/FLAC nei download da link diretti o ricerca ISRC.",
                    "type": "string",
                    "example": "Taylor Swift"
                },
                "album_name": {
                    "description": "Nome dell'album. Facoltativo, usato per la scrittura dei tag ID3/FLAC nei download da link diretti o ricerca ISRC.",
                    "type": "string",
                    "example": "Reputation"
                },
                "artist_name": {
                    "description": "Nome dell'artista principale. Obbligatorio solo se non viene fornito un URL. Nei link diretti, serve come metadato di fallback.",
                    "type": "string",
                    "example": "Taylor Swift"
                },
                "filename_format": {
                    "description": "Formato di salvataggio per il nome del file. Supporta tag dinamici come {artist}, {title}, {album}. Default: \"{artist} - {title}\"",
                    "type": "string",
                    "example": "{artist} - {title}"
                },
                "isrc": {
                    "description": "Codice ISRC (International Standard Recording Code) del brano. Obbligatorio solo per il download diretto tramite metadati (se non viene fornito un URL).",
                    "type": "string",
                    "example": "USUM71703861"
                },
                "output_dir": {
                    "description": "Cartella sul server in cui salvare i file musicali scaricati. Default: \"./downloads\"",
                    "type": "string",
                    "example": "./downloads"
                },
                "quality": {
                    "description": "Qualità del download. Per Qobuz (es. \"6\" per Hi-Res). Per Tidal/Amazon (es. \"LOSSLESS\" per qualità CD FLAC). Se omesso, viene applicato un valore predefinito ottimale.",
                    "type": "string",
                    "example": "6"
                },
                "release_date": {
                    "description": "Data di pubblicazione del brano (es. YYYY-MM-DD). Facoltativo, usato per i tag ID3/FLAC.",
                    "type": "string",
                    "example": "2017-08-24"
                },
                "service": {
                    "description": "Servizio di streaming musicale di destinazione da cui effettuare il download effettivo dei file.\n@Enums qobuz, tidal, amazon",
                    "type": "string",
                    "example": "qobuz"
                },
                "spotify_id": {
                    "description": "ID Spotify del brano. Facoltativo, utile come riferimento per collegare l'ISRC in caso di download diretto senza URL.",
                    "type": "string",
                    "example": "1OCaN2Vv7f7F1QGq5Q7P9H"
                },
                "track_name": {
                    "description": "Titolo del brano. Obbligatorio solo se non viene fornito un URL. Nei link diretti, serve come metadato di fallback.",
                    "type": "string",
                    "example": "Look What You Made Me Do"
                },
                "url": {
                    "description": "URL del brano, album, playlist o artista da scaricare. Supporta link Spotify (es. https://open.spotify.com/track/...) oppure link diretti Tidal, Amazon Music o Qobuz. Obbligatorio a meno che non si specifichi la triade isrc, track_name e artist_name.",
                    "type": "string",
                    "example": "https://open.spotify.com/track/4PTG3Z6ehGkBFmzsOhswXP"
                }
            }
        },
        "models.Task": {
            "type": "object",
            "properties": {
                "completed_tracks": {
                    "type": "integer"
                },
                "created_at": {
                    "type": "string"
                },
                "current_track": {
                    "type": "string"
                },
                "downloaded_files": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "error": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "quality": {
                    "type": "string"
                },
                "service": {
                    "type": "string"
                },
                "spotify_url": {
                    "type": "string"
                },
                "status": {
                    "$ref": "#/definitions/models.TaskStatus"
                },
                "total_tracks": {
                    "type": "integer"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "models.TaskStatus": {
            "type": "string",
            "enum": [
                "pending",
                "resolving",
                "downloading",
                "completed",
                "failed"
            ],
            "x-enum-varnames": [
                "StatusPending",
                "StatusResolving",
                "StatusDownloading",
                "StatusCompleted",
                "StatusFailed"
            ]
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "SpotiFLAC REST API",
	Description:      "A lightweight REST API wrapper for the SpotiFLAC backend.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
